version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
      - 8000:8000
    restart: unless-stopped
  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - $PWD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.size=10GB" # Comment this line to revert back to the default retention size.
      - "--storage.tsdb.retention.time=1y" # Comment this line to revert back to the default retention time.
    restart: unless-stopped
  json_exporter:
    image: quay.io/prometheuscommunity/json-exporter:v0.5.0
    container_name: json_exporter
    volumes:
      - $PWD/prometheus/exporters/json_exporter/config.yml:/config.yml:ro
    ports:
      - 7979:7979
    restart: unless-stopped
  adsbx_exporter:
    build:
      context: ./prometheus/exporters/adsbx_exporter
      dockerfile: Dockerfile
    container_name: adsbx_exporter
    ports:
      - 19100:19100
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/aggregators_dashboard.json"
      # GF_SECURITY_ALLOW_EMBEDDING: true # Uncomment this line to allow embedding of Grafana dashboards.
      # GF_AUTH_ANONYMOUS_ENABLED: true # Uncomment this line to allow anonymous access to Grafana.
      # GF_AUTH_ANONYMOUS_HIDE_VERSION: true # Uncomment this line to hide the version number from the Grafana UI.
      # GF_AUTH_ANONYMOUS_ORG_NAME: "ADSB.cool" # Uncomment this line to set the name of the organization.
    restart: unless-stopped

volumes:
  portainer_data:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: adsb-dashboards
