global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: adsb_fi_exporter
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["adsb-fi"]
    static_configs:
      - targets:
          - https://api.adsb.fi/v1/stats
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement:  json_exporter:7979
  - job_name: adsb_lol_exporter
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["adsb-lol"]
    static_configs:
      - targets:
          - https://adsb.lol/api/0/me
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement:  json_exporter:7979

# Uncomment if you want to send data to grafana cloud
# remote_write:
# - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
#   basic_auth:
#     username: 
#     password: 
